import daScore from "./daScore";
import kukiScore from "./kukiScore";
import uniScore from "./uniScore";

let songs = [
  {
    artist: "3 Doors Down",
    name: "Kryptonite",
    year: 2000,
    link: "https://www.youtube.com/watch?v=xPU8OAjjS4k&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=1",
  },
  {
    artist: "3OH!3",
    name: "Don't Trust Me",
    year: 2008,
    link: "https://www.youtube.com/watch?v=mdB3Oyd5HtU&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=2",
  },
  {
    artist: "50 Cent",
    name: "In Da Club",
    year: 2003,
    link: "https://www.youtube.com/watch?v=5qm8PH4xAss&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=3",
  },
  {
    artist: "A Touch Of Class",
    name: "Around The World",
    year: 2000,
    link: "https://www.youtube.com/watch?v=Se237UXFKlQ&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=4",
  },
  {
    artist: "Adam Lambert",
    name: "Whataya Want from Me",
    year: 2009,
    link: "https://www.youtube.com/watch?v=X1Fqn9du7xo&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=5",
  },
  {
    artist: "Adele",
    name: "Chasing Pavements",
    year: 2008,
    link: "https://www.youtube.com/watch?v=08DjMT-qR9g&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=6",
  },
  {
    artist: "Afroman",
    name: "Because I got high",
    year: 2000,
    link: "https://www.youtube.com/watch?v=WeYsTmIzjkw&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=7",
  },
  {
    artist: "Agnes",
    name: "Release me",
    year: 2008,
    link: "https://www.youtube.com/watch?v=keYXzDh5JEQ&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=8",
  },
  {
    artist: "Akon",
    name: "Lonely",
    year: 2003,
    link: "https://www.youtube.com/watch?v=6EEW-9NDM5k&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=9",
  },
  {
    artist: "Alicia Keys",
    name: "Fallin'",
    year: 2001,
    link: "https://www.youtube.com/watch?v=Urdlvw0SSEc&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=10",
  },
  {
    artist: "Alien Ant Farm",
    name: "Smooth Criminal",
    year: 2001,
    link: "https://www.youtube.com/watch?v=CDl9ZMfj6aE&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=11",
  },
  {
    artist: "Amerie",
    name: "1 Thing",
    year: 2004,
    link: "https://www.youtube.com/watch?v=bbqVg_23otg&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=12",
  },
  {
    artist: "Amy Winehouse",
    name: "Back To Black",
    year: 2006,
    link: "https://www.youtube.com/watch?v=TJAfLE39ZZ8&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=13",
  },
  {
    artist: "Anastacia",
    name: "I'm Outta Love",
    year: 2000,
    link: "https://www.youtube.com/watch?v=TnOy6HEf7HU&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=14",
  },
  {
    artist: "Atomic Kitten",
    name: "The Tide is High",
    year: 2001,
    link: "https://www.youtube.com/watch?v=u8CMsQ-p1ls&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=15",
  },
  {
    artist: "Avril Lavigne",
    name: "Complicated",
    year: 2002,
    link: "https://www.youtube.com/watch?v=5NPBIwQyPWE&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=16",
  },
  {
    artist: "Backstreet Boys",
    name: "Incomplete",
    year: 2005,
    link: "https://www.youtube.com/watch?v=WVe80iZtlYU&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=17",
  },
  {
    artist: "Basement Jaxx",
    name: "Where's Your Head At",
    year: 2001,
    link: "https://www.youtube.com/watch?v=5rAOyh7YmEc&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=18",
  },
  {
    artist: "Basshunter",
    name: "Boten Anna",
    year: 2006,
    link: "https://www.youtube.com/watch?v=1XK5-n4rR7Q&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=19",
  },
  {
    artist: "Beyonce ft. Jay-Z",
    name: "Crazy In Love",
    year: 2003,
    link: "https://www.youtube.com/watch?v=ViwtNLUqkMY&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=20",
  },
  {
    artist: "Black Eyed Peas",
    name: "Let's Get It Started",
    year: 2003,
    link: "https://www.youtube.com/watch?v=IKqV7DB8Iwg&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=21",
  },
  {
    artist: "Blink-182",
    name: "I Miss You",
    year: 2004,
    link: "https://www.youtube.com/watch?v=s1tAYmMjLdY&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=22",
  },
  {
    artist: "Bloodhound Gang",
    name: "Foxtrot Unicorn Charlie Kilo",
    year: 2005,
    link: "https://www.youtube.com/watch?v=JZpxaiNV_sM&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=23",
  },
  {
    artist: "Blue",
    name: "All Rise",
    year: 2001,
    link: "https://www.youtube.com/watch?v=RkWQDDv_qdg&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=24",
  },
  {
    artist: "Bob Sinclar",
    name: "Rock This Party",
    year: 2006,
    link: "https://www.youtube.com/watch?v=6wOfzs7lSFc&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=25",
  },
  {
    artist: "Bon Jovi",
    name: "It's My Life",
    year: 2000,
    link: "https://www.youtube.com/watch?v=vx2u5uUu3DE&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=26",
  },
  {
    artist: "Bowling For Soup",
    name: "1985",
    year: 2004,
    link: "https://www.youtube.com/watch?v=K38xNqZvBJI&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=27",
  },
  {
    artist: "Breaking Benjamin",
    name: "The Diary of Jane",
    year: 2006,
    link: "https://www.youtube.com/watch?v=DWaB4PXCwFU&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=28",
  },
  {
    artist: "Britney Spears",
    name: "Toxic",
    year: 2003,
    link: "https://www.youtube.com/watch?v=LOZuxwVk7TU&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=29",
  },
  {
    artist: "Busted",
    name: "Year 3000",
    year: 2002,
    link: "https://www.youtube.com/watch?v=Tu7HoGZaspo&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=30",
  },
  {
    artist: "Cascada",
    name: "Everytime We Touch",
    year: 2005,
    link: "https://www.youtube.com/watch?v=4G6QDNC4jPs&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=31",
  },
  {
    artist: "Céline Dion",
    name: "I'm Alive",
    year: 2000,
    link: "https://www.youtube.com/watch?v=NJsa6-y4sDs&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=32",
  },
  {
    artist: "Chamilionaire ft Krayzie Bone",
    name: "Ridin'",
    year: 2005,
    link: "https://www.youtube.com/watch?v=CtwJvgPJ9xw&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=33",
  },
  {
    artist: "Chingy",
    name: "Right Thurr",
    year: 2003,
    link: "https://www.youtube.com/watch?v=iO476kD-k0g&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=34",
  },
  {
    artist: "Chris Brown",
    name: "Forever",
    year: 2007,
    link: "https://www.youtube.com/watch?v=5sMKX22BHeE&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=35",
  },
  {
    artist: "Christina Aguilera (ft. Lil' Kim, Mya & Pink)",
    name: "Lady Marmalade",
    year: 2001,
    link: "https://www.youtube.com/watch?v=RQa7SvVCdZk&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=36",
  },
  {
    artist: "Christina Milian",
    name: "Dip It Low",
    year: 2005,
    link: "https://www.youtube.com/watch?v=5z5Mvyp1QHw&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=37",
  },
  {
    artist: "Ciara (feat. Missy Elliot)",
    name: "1,2, Step",
    year: 2004,
    link: "https://www.youtube.com/watch?v=iBHNgV6_znU&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=38",
  },
  {
    artist: "Colbie Caillat",
    name: "Bubbly",
    year: 2007,
    link: "https://www.youtube.com/watch?v=AWGqoCNbsvM&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=39",
  },
  {
    artist: "Coldplay",
    name: "Clocks",
    year: 2002,
    link: "https://www.youtube.com/watch?v=d020hcWA_Wg&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=40",
  },
  {
    artist: "Corinne Bailey Rae",
    name: "Put Your Records On",
    year: 2006,
    link: "https://www.youtube.com/watch?v=rjOhZZyn30k&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=41",
  },
  {
    artist: "Craig David",
    name: "7 Days",
    year: 2000,
    link: "https://www.youtube.com/watch?v=P5lmb5-tnM0&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=42",
  },
  {
    artist: "Crazy Frog",
    name: "Axel F",
    year: 2003,
    link: "https://www.youtube.com/watch?v=k85mRPqvMbE&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=43",
  },
  {
    artist: "Creed",
    name: "One Last Breath",
    year: 2001,
    link: "https://www.youtube.com/watch?v=qnkuBUAwfe0&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=44",
  },
  {
    artist: "Crazy Town",
    name: "Butterfly",
    year: 2000,
    link: "https://www.youtube.com/watch?v=6FEDrU85FLE&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=45",
  },
  {
    artist: "Daddy Yankee",
    name: "Gasolina",
    year: 2004,
    link: "https://www.youtube.com/watch?v=CCF1_jI8Prk&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=46",
  },
  {
    artist: "Daft Punk",
    name: "One More Time",
    year: 2000,
    link: "https://www.youtube.com/watch?v=FGBhQbmPwH8&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=47",
  },
  {
    artist: "Daniel Bedingfield",
    name: "If You're Not The One",
    year: 2002,
    link: "https://www.youtube.com/watch?v=j6nevGNYTkA&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=48",
  },
  {
    artist: "Daniel Merriweather",
    name: "Red",
    year: 2009,
    link: "https://www.youtube.com/watch?v=o1NCmDYeymo&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=49",
  },
  {
    artist: "Daniel Powter",
    name: "Bad Day",
    year: 2005,
    link: "https://www.youtube.com/watch?v=gH476CxJxfg&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=50",
  },
  {
    artist: "Danzel",
    name: "Pump It Up",
    year: 2004,
    link: "https://www.youtube.com/watch?v=0HtyF0jux2Q&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=51",
  },
  {
    artist: "Darude",
    name: "Sandstorm",
    year: 2000,
    link: "https://www.youtube.com/watch?v=y6120QOlsfU&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=52",
  },
  {
    artist: "David Guetta Vs. The Egg",
    name: "Love Don't Let Me Go",
    year: 2002,
    link: "https://www.youtube.com/watch?v=L0VmaJsPWbY&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=53",
  },
  {
    artist: "Destiny's Child",
    name: "Survivor",
    year: 2001,
    link: "https://www.youtube.com/watch?v=Wmc8bQoL-J0&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=54",
  },
  {
    artist: "Dido",
    name: "White Flag",
    year: 2003,
    link: "https://www.youtube.com/watch?v=j-fWDrZSiZs&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=55",
  },
  {
    artist: "Dr. Dre ft Snoop Dogg, Kurupt, Nate Dogg",
    name: "The Next Episode",
    year: 2001,
    link: "https://www.youtube.com/watch?v=QZXc39hT8t4&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=56",
  },
  {
    artist: "Duffy",
    name: "Mercy",
    year: 2008,
    link: "https://www.youtube.com/watch?v=y7ZEVA5dy-Y&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=57",
  },
  {
    artist: "Edward Maya & Vika Jigulina",
    name: "Stereo Love",
    year: 2009,
    link: "https://www.youtube.com/watch?v=p-Z3YrHJ1sU&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=58",
  },
  {
    artist: "Edward Sharpe and the Magnetic Zeros",
    name: "Home",
    year: 2009,
    link: "https://www.youtube.com/watch?v=DHEOF_rcND8&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=59",
  },
  {
    artist: "Eminem",
    name: "The Real Slim Shady",
    year: 2000,
    link: "https://www.youtube.com/watch?v=eJO5HU_7_1w&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=60",
  },
  {
    artist: "Enrique Iglesias",
    name: "Hero",
    year: 2001,
    link: "https://www.youtube.com/watch?v=koJlIGDImiU&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=61",
  },
  {
    artist: "Eric Prydz",
    name: "Pjanoo",
    year: 2008,
    link: "https://www.youtube.com/watch?v=ByXbXg-Zny8&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=62",
  },
  {
    artist: "Evanescence ft. Paul McCoy",
    name: "Bring Me To Life",
    year: 2003,
    link: "https://www.youtube.com/watch?v=3YxaaGgTQYM&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=63",
  },
  {
    artist: "Fall Out Boy",
    name: "Dance, Dance",
    year: 2005,
    link: "https://www.youtube.com/watch?v=C6MOKXm8x50&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=64",
  },
  {
    artist: "Fatman Scoop",
    name: "Be Faithful",
    year: 2003,
    link: "https://www.youtube.com/watch?v=SmnEhmjgZ9s&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=65",
  },
  {
    artist: "Flo Rida ft. Ke$ha",
    name: "Right Round",
    year: 2009,
    link: "https://www.youtube.com/watch?v=CcCw1ggftuQ&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=66",
  },
  {
    artist: "Foo Fighters",
    name: "The Pretender",
    year: 2007,
    link: "https://www.youtube.com/watch?v=SBjQ9tuuTJQ&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=67",
  },
  {
    artist: "Franz Ferdinand",
    name: "Take Me Out",
    year: 2004,
    link: "https://www.youtube.com/watch?v=Ijk4j-r7qPA&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=68",
  },
  {
    artist: "Gavin DeGraw",
    name: "I Don't Want to Be",
    year: 2003,
    link: "https://www.youtube.com/watch?v=8gFCW3PHBws&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=69",
  },
  {
    artist: "Gnarls Barkley",
    name: "Crazy",
    year: 2006,
    link: "https://www.youtube.com/watch?v=-N4jf6rtyuw&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=70",
  },
  {
    artist: "Gorillaz",
    name: "Feel Good Inc.",
    year: 2004,
    link: "https://www.youtube.com/watch?v=HyHNuVaZJ-k&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=71",
  },
  {
    artist: "Green Day",
    name: "Boulevard Of Broken Dreams",
    year: 2004,
    link: "https://www.youtube.com/watch?v=Soa3gO7tL-c&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=72",
  },
  {
    artist: "Guru Josh Project (Klaas Vocal Mix)",
    name: "Infinity ",
    year: 2008,
    link: "https://www.youtube.com/watch?v=jzy2dgEUOhY&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=73",
  },
  {
    artist: "Gym Class Heroes ft. Patrick Stump",
    name: "Cupid's Chokehold",
    year: 2005,
    link: "https://www.youtube.com/watch?v=eiiU-Fky18s&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=74",
  },
  {
    artist: "Gwen Stefani ft. Eve",
    name: "Rich Girl",
    year: 2004,
    link: "https://www.youtube.com/watch?v=9rlNpWYQunY&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=75",
  },
  {
    artist: "Hoobastank",
    name: "The Reason",
    year: 2004,
    link: "https://www.youtube.com/watch?v=fV4DiAyExN0&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=76",
  },
  {
    artist: "Ida Corr feat. Fedde Le Grand",
    name: "Let Me Think About It",
    year: 2006,
    link: "https://www.youtube.com/watch?v=7gkhE7t4KCE&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=77",
  },
  {
    artist: "Jason Mraz",
    name: "I'm Yours",
    year: 2008,
    link: "https://www.youtube.com/watch?v=EkHTsc9PU2A&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=78",
  },
  {
    artist: "JAY-Z",
    name: "99 Problems",
    year: 2003,
    link: "https://www.youtube.com/watch?v=6uikJTnmtgw&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=79",
  },
  {
    artist: "Jamelia",
    name: "Superstar",
    year: 2003,
    link: "https://www.youtube.com/watch?v=Bu0LKfB3CR8&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=80",
  },
  {
    artist: "James Blunt",
    name: "You're Beautiful",
    year: 2004,
    link: "https://www.youtube.com/watch?v=oofSnsGkops&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=81",
  },
  {
    artist: "Jason Derulo",
    name: "Whatcha Say",
    year: 2009,
    link: "https://www.youtube.com/watch?v=pBI3lc18k8Q&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=82",
  },
  {
    artist: "Jay Sean ft. Lil Wayne",
    name: "Down",
    year: 2009,
    link: "https://www.youtube.com/watch?v=oUbpGmR1-QM&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=83",
  },
  {
    artist: "Jennifer Lopez",
    name: "Jenny From The Block",
    year: 2002,
    link: "https://www.youtube.com/watch?v=dly6p4Fu5TE&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=84",
  },
  {
    artist: "Jeremih",
    name: "Birthday Sex",
    year: 2009,
    link: "https://www.youtube.com/watch?v=vYMxOzxKYYo&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=85",
  },
  {
    artist: "Jimmy Eat World",
    name: "The Middle",
    year: 2001,
    link: "https://www.youtube.com/watch?v=oKsxPW6i3pM&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=86",
  },
  {
    artist: "John Mayer",
    name: "Your Body Is A Wonderland",
    year: 2001,
    link: "https://www.youtube.com/watch?v=N5EnGwXV_Pg&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=87",
  },
  {
    artist: "Johnny Cash",
    name: "Hurt",
    year: 2003,
    link: "https://www.youtube.com/watch?v=8AHCfZTRGiI&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=88",
  },
  {
    artist: "JoJo",
    name: "Leave (Get Out)",
    year: 2004,
    link: "https://www.youtube.com/watch?v=fWzoSy6QEwk&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=89",
  },
  {
    artist: "Jordin Sparks ft. Chris Brown",
    name: "No Air",
    year: 2008,
    link: "https://www.youtube.com/watch?v=WBKnpyoFEBo&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=90",
  },
  {
    artist: "Juanes",
    name: "La Camisa Negra",
    year: 2004,
    link: "https://www.youtube.com/watch?v=kRt2sRyup6A&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=91",
  },
  {
    artist: "Junior Senior",
    name: "Move Your Feet",
    year: 2002,
    link: "https://www.youtube.com/watch?v=SPlQpGeTbIE&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=92",
  },
  {
    artist: "Justin Bieber",
    name: "Baby",
    year: 2009,
    link: "https://www.youtube.com/watch?v=kffacxfA7G4&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=93",
  },
  {
    artist: "Justin Timberlake",
    name: "Rock Your Body",
    year: 2002,
    link: "https://www.youtube.com/watch?v=TSVHoHyErBQ&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=94",
  },
  {
    artist: "Kanye West ft. Jamie Foxx",
    name: "Gold Digger",
    year: 2005,
    link: "https://www.youtube.com/watch?v=6vwNcNOTVzY&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=95",
  },
  {
    artist: "Katie Melua",
    name: "Nine Millions Bicycles",
    year: 2006,
    link: "https://www.youtube.com/watch?v=rrPUJsZQSkw&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=96",
  },
  {
    artist: "Katy Perry",
    name: "I Kissed A Girl",
    year: 2008,
    link: "https://www.youtube.com/watch?v=tAp9BKosZXs&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=97",
  },
  {
    artist: "Keane",
    name: "Everybody's Changing",
    year: 2006,
    link: "https://www.youtube.com/watch?v=RSNmgE6L8AU&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=98",
  },
  {
    artist: "Kelis",
    name: "Milkshake",
    year: 2003,
    link: "https://www.youtube.com/watch?v=6AwXKJoKJz4&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=99",
  },
  {
    artist: "Kelly Clarkson",
    name: "Because Of You",
    year: 2004,
    link: "https://www.youtube.com/watch?v=Ra-Om7UMSJc&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=100",
  },
  {
    artist: "Kevin Rolf ft. Lil Wayne",
    name: "Let It Rock",
    year: 2008,
    link: "https://www.youtube.com/watch?v=u0n4eMGXAyk&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=101",
  },
  {
    artist: "Kevin Lyttle",
    name: "Turn Me On",
    year: 2003,
    link: "https://www.youtube.com/watch?v=GP3Exc5tCtc&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=102",
  },
  {
    artist: "Kid Cudi",
    name: "Day 'n' Nite",
    year: 2008,
    link: "https://www.youtube.com/watch?v=VrDfSZ_6f4U&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=103",
  },
  {
    artist: "Kid Rock",
    name: "All Summer Long",
    year: 2007,
    link: "https://www.youtube.com/watch?v=aSkFygPCTwE&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=104",
  },
  {
    artist: "Kings of Leon",
    name: "Use Somebody",
    year: 2008,
    link: "https://www.youtube.com/watch?v=gnhXHvRoUd0&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=105",
  },
  {
    artist: "KT Tunstall",
    name: "Suddenly I See",
    year: 2004,
    link: "https://www.youtube.com/watch?v=9AEoUa0Hlso&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=106",
  },
  {
    artist: "Kylie Minogue",
    name: "Can't Get You Out Of My Head",
    year: 2001,
    link: "https://www.youtube.com/watch?v=c18441Eh_WE&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=107",
  },
  {
    artist: "Lady Antebellum",
    name: "Need You Now ",
    year: 2009,
    link: "https://www.youtube.com/watch?v=eM213aMKTHg&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=108",
  },
  {
    artist: "Lady Gaga ft. Colby O'Donis",
    name: "Just Dance",
    year: 2008,
    link: "https://www.youtube.com/watch?v=2Abk1jAONjw&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=109",
  },
  {
    artist: "Las Ketchup",
    name: "The Ketchup Song",
    year: 2002,
    link: "https://www.youtube.com/watch?v=AMT698ArSfQ&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=110",
  },
  {
    artist: "LeeAnn Rimes",
    name: "Can't Fight The Moonlight",
    year: 2000,
    link: "https://www.youtube.com/watch?v=bx3s99FNXzI&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=111",
  },
  {
    artist: "Leona Lewis",
    name: "Bleeding Love",
    year: 2007,
    link: "https://www.youtube.com/watch?v=7_weSk0BonM&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=112",
  },
  {
    artist: "Lifehouse",
    name: "Hanging By A Moment",
    year: 2000,
    link: "https://www.youtube.com/watch?v=tPnK39ax_AM&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=113",
  },
  {
    artist: "Lil Jon & The East Side Boyz ft. Ying Yang Twins",
    name: "Get Low",
    year: 2003,
    link: "https://www.youtube.com/watch?v=IYH7_GzP4Tg&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=114",
  },
  {
    artist: "Lily Allen",
    name: "Smile",
    year: 2008,
    link: "https://www.youtube.com/watch?v=0WxDrVUrSvI&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=115",
  },
  {
    artist: "Limp Bizkit",
    name: "Behind Blue Eyes",
    year: 2003,
    link: "https://www.youtube.com/watch?v=DOV7mm3zHZ4&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=116",
  },
  {
    artist: "Linkin Park",
    name: "In The End",
    year: 2000,
    link: "https://www.youtube.com/watch?v=eVTXPUF4Oz4&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=117",
  },
  {
    artist: "Lloyd ft Lil Wayne",
    name: "You",
    year: 2006,
    link: "https://www.youtube.com/watch?v=YVLHaqeJzEk&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=118",
  },
  {
    artist: "Lumidee ft. Busta Rhymes & Fabulous",
    name: "Never Leave You (Uh Oooh, Uh Oooh)",
    year: 2003,
    link: "https://www.youtube.com/watch?v=QhKj93rPIDo&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=119",
  },
  {
    artist: "M.I.A",
    name: "Paper Planes",
    year: 2007,
    link: "https://www.youtube.com/watch?v=ewRjZoRtu0Y&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=120",
  },
  {
    artist: "Madonna",
    name: "Hung Up",
    year: 2005,
    link: "https://www.youtube.com/watch?v=EDwb9jOVRtU&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=121",
  },
  {
    artist: "Mariah Carey",
    name: "We Belong Together",
    year: 2005,
    link: "https://www.youtube.com/watch?v=0habxsuXW4g&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=122",
  },
  {
    artist: "Mario",
    name: "Let Me Love You",
    year: 2004,
    link: "https://www.youtube.com/watch?v=H64QG4UsrGI&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=123",
  },
  {
    artist: "Maroon 5",
    name: "She Will Be Loved",
    year: 2002,
    link: "https://www.youtube.com/watch?v=nIjVuRTm-dc&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=124",
  },
  {
    artist: "Mary J. Blige",
    name: "Family Affair",
    year: 2001,
    link: "https://www.youtube.com/watch?v=znlFu_lemsU&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=125",
  },
  {
    artist: "MGMT",
    name: "Kids",
    year: 2007,
    link: "https://www.youtube.com/watch?v=fe4EK4HSPkI&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=126",
  },
  {
    artist: "Michael Bublé",
    name: "Haven't Met You Yet",
    year: 2009,
    link: "https://www.youtube.com/watch?v=1AJmKkU5POA&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=127",
  },
  {
    artist: "MIKA",
    name: "Grace Kelly",
    year: 2007,
    link: "https://www.youtube.com/watch?v=0CGVgAYJyjk&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=128",
  },
  {
    artist: "Miley Cyrus",
    name: "Party In The USA",
    year: 2009,
    link: "https://www.youtube.com/watch?v=M11SvDtPBhA&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=129",
  },
  {
    artist: "Mims",
    name: "This Is Why I'm Hot",
    year: 2007,
    link: "https://www.youtube.com/watch?v=TwyE3WJ4AWo&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=130",
  },
  {
    artist: "Missy Elliott",
    name: "Work It",
    year: 2002,
    link: "https://www.youtube.com/watch?v=cjIvu7e6Wq8&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=131",
  },
  {
    artist: "Modjo",
    name: "Lady - Hear Me Tonight",
    year: 2000,
    link: "https://www.youtube.com/watch?v=mMfxI3r_LyA&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=132",
  },
  {
    artist: "Muse",
    name: "Uprising",
    year: 2009,
    link: "https://www.youtube.com/watch?v=w8KQmps-Sog&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=133",
  },
  {
    artist: "My Chemical Romance",
    name: "Welcome To The Black Parade",
    year: 2006,
    link: "https://www.youtube.com/watch?v=RRKJiM9Njr8&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=134",
  },
  {
    artist: "Natasha Bedingfeld",
    name: "Unwritten",
    year: 2004,
    link: "https://www.youtube.com/watch?v=b7k0a5hYnSI&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=135",
  },
  {
    artist: "Ne-Yo",
    name: "So Sick",
    year: 2006,
    link: "https://www.youtube.com/watch?v=IxszlJppRQI&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=136",
  },
  {
    artist: "Nelly",
    name: "Hot In Here",
    year: 2002,
    link: "https://www.youtube.com/watch?v=GeZZr_p6vB8&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=137",
  },
  {
    artist: "Nelly Furtado",
    name: "I'm Like A Bird",
    year: 2000,
    link: "https://www.youtube.com/watch?v=roPQ_M3yJTA&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=138",
  },
  {
    artist: "Nickelback",
    name: "How You Remind Me",
    year: 2001,
    link: "https://www.youtube.com/watch?v=Aiay8I5IPB8&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=139",
  },
  {
    artist: "Norah Jones",
    name: "Don't Know Why",
    year: 2002,
    link: "https://www.youtube.com/watch?v=tO4dxvguQDk&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=140",
  },
  {
    artist: "*NSYNC",
    name: "Bye Bye Bye",
    year: 2000,
    link: "https://www.youtube.com/watch?v=Eo-KmOd3i7s&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=141",
  },
  {
    artist: "O-Zone",
    name: "Dragostea Din Tei",
    year: 2003,
    link: "https://www.youtube.com/watch?v=YnopHCL1Jk8&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=142",
  },
  {
    artist: "Omarion",
    name: "Ice Box",
    year: 2006,
    link: "https://www.youtube.com/watch?v=jQybgJCswF0&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=143",
  },
  {
    artist: "One-T + Cool T",
    name: "The Magic Key",
    year: 2002,
    link: "https://www.youtube.com/watch?v=TQV-0fwwCQM&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=144",
  },
  {
    artist: "OneRepublic",
    name: "Stop And Stare",
    year: 2007,
    link: "https://www.youtube.com/watch?v=HtNS1afUOnE&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=145",
  },
  {
    artist: "Outkast",
    name: "Hey Ya!",
    year: 2003,
    link: "https://www.youtube.com/watch?v=PWgvGjAhvIw&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=146",
  },
  {
    artist: "Owl City",
    name: "Fireflies",
    year: 2009,
    link: "https://www.youtube.com/watch?v=psuRGfAaju4&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=147",
  },
  {
    artist: "Panic! At The Disco",
    name: "I Write Sins Not Tradegies",
    year: 2005,
    link: "https://www.youtube.com/watch?v=vc6vs-l5dkc&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=148",
  },
  {
    artist: "Papa Roach",
    name: "Last Resort",
    year: 2000,
    link: "https://www.youtube.com/watch?v=j0lSpNtjPM8&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=149",
  },
  {
    artist: "Pink",
    name: "U + Ur Hand",
    year: 2006,
    link: "https://www.youtube.com/watch?v=YUtHjOvPKT0&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=150",
  },
  {
    artist: "Plain White-T's",
    name: "Hey There Delilah",
    year: 2006,
    link: "https://www.youtube.com/watch?v=h_m-BjrxmgI&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=151",
  },
  {
    artist: "Puddle of Mudd",
    name: "Blurry",
    year: 2001,
    link: "https://www.youtube.com/watch?v=xJJsoquu70o&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=152",
  },
  {
    artist: "Rammstein",
    name: "Sonne",
    year: 2001,
    link: "https://www.youtube.com/watch?v=StZcUAPRRac&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=153",
  },
  {
    artist: "Red Hot Chili Peppers",
    name: "Dani California",
    year: 2006,
    link: "https://www.youtube.com/watch?v=Sb5aq5HcS1A&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=154",
  },
  {
    artist: "Ricky Martin",
    name: "She Bangs",
    year: 2000,
    link: "https://www.youtube.com/watch?v=5ihtX86JzmA&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=155",
  },
  {
    artist: "Rihanna ft. Jay-Z",
    name: "Umbrella",
    year: 2007,
    link: "https://www.youtube.com/watch?v=CvBfHwUxHIk&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=156",
  },
  {
    artist: "Rob Thomas",
    name: "Lonely No More",
    year: 2005,
    link: "https://www.youtube.com/watch?v=7spBU4Yv8fE&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=157",
  },
  {
    artist: "Ronan Keating",
    name: "Life Is A Rollingcoaster",
    year: 2000,
    link: "https://www.youtube.com/watch?v=z5a1xk61wfg&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=158",
  },
  {
    artist: "Robbie Williams",
    name: "Feel",
    year: 2002,
    link: "https://www.youtube.com/watch?v=iy4mXZN1Zzk&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=159",
  },
  {
    artist: "Sade",
    name: "By Your Side",
    year: 2000,
    link: "https://www.youtube.com/watch?v=C8QJmI_V3j4&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=160",
  },
  {
    artist: "Safri Duo",
    name: "The Bongo Song",
    year: 2000,
    link: "https://www.youtube.com/watch?v=IksRDCMYnn8&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=161",
  },
  {
    artist: "Sara Bareilles",
    name: "Love Song",
    year: 2007,
    link: "https://www.youtube.com/watch?v=qi7Yh16dA0w&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=162",
  },
  {
    artist: "Sean Kingston",
    name: "Beautiful Girls",
    year: 2007,
    link: "https://www.youtube.com/watch?v=MrTz5xjmso4&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=163",
  },
  {
    artist: "Sean Paul",
    name: "Get Busy",
    year: 2003,
    link: "https://www.youtube.com/watch?v=oPQ3o14ksaM&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=164",
  },
  {
    artist: "Shaggy",
    name: "It Wasn't Me",
    year: 2000,
    link: "https://www.youtube.com/watch?v=2g5Hz17C4is&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=165",
  },
  {
    artist: "Shakira",
    name: "Whenever, Wherever",
    year: 2001,
    link: "https://www.youtube.com/watch?v=weRHyjj34ZE&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=166",
  },
  {
    artist: "Snoop Dog ft. Pharell Williams",
    name: "Drop It Like It's Hot",
    year: 2004,
    link: "https://www.youtube.com/watch?v=GtUVQei3nX4&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=167",
  },
  {
    artist: "Sophie Ellis-Bextor",
    name: "Murder On The Dancefloor",
    year: 2001,
    link: "https://www.youtube.com/watch?v=hAx6mYeC6pY&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=168",
  },
  {
    artist: "Soulja Boy Tell 'em",
    name: "Crank That (Soulja Boy)",
    year: 2007,
    link: "https://www.youtube.com/watch?v=8UFIYGkROII&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=169",
  },
  {
    artist: "Stacie Orrico",
    name: "There's Gotta Be More To Life",
    year: 2003,
    link: "https://www.youtube.com/watch?v=wUOcQnWbk_U&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=170",
  },
  {
    artist: "Staind",
    name: "Its Been Awhile",
    year: 2001,
    link: "https://www.youtube.com/watch?v=araU0fZj6oQ&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=171",
  },
  {
    artist: "Sugababes",
    name: "Push The Button",
    year: 2005,
    link: "https://www.youtube.com/watch?v=oJDGcxAf9D8&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=172",
  },
  {
    artist: "Sum 41",
    name: "Still Waiting",
    year: 2002,
    link: "https://www.youtube.com/watch?v=qO-mSLxih-c&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=173",
  },
  {
    artist: "System of a Down",
    name: "Chop Suey!",
    year: 2001,
    link: "https://www.youtube.com/watch?v=CSvFpBOe8eY&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=174",
  },
  {
    artist: "t.A.T.u",
    name: "All The Things She Said",
    year: 2002,
    link: "https://www.youtube.com/watch?v=8mGBaXPlri8&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=175",
  },
  {
    artist: "T.I",
    name: "Whatever You Like",
    year: 2008,
    link: "https://www.youtube.com/watch?v=nQJACVmankY&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=176",
  },
  {
    artist: "Taio Cruz ft. Ludacris",
    name: "Break Your Heart",
    year: 2009,
    link: "https://www.youtube.com/watch?v=y_SI2EDM6Lo&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=177",
  },
  {
    artist: "Taylor Swift",
    name: "Love Story",
    year: 2008,
    link: "https://www.youtube.com/watch?v=8xg3vE8Ie_E&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=178",
  },
  {
    artist: "Terror Squad ft. Fat Joe & Remy Ma",
    name: "Lean Back",
    year: 2004,
    link: "https://www.youtube.com/watch?v=ajmI1P3r1w4&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=179",
  },
  {
    artist: "The All-American Rejects",
    name: "Gives You Hell",
    year: 2008,
    link: "https://www.youtube.com/watch?v=uxUATkpMQ8A&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=180",
  },
  {
    artist: "The Calling",
    name: "Wherever You Will Go",
    year: 2001,
    link: "https://www.youtube.com/watch?v=iAP9AF6DCu4&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=181",
  },
  {
    artist: "The Fray",
    name: "How To Save A Life",
    year: 2005,
    link: "https://www.youtube.com/watch?v=cjVQ36NhbMk&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=182",
  },
  {
    artist: "The Rasmus",
    name: "In The Shadows",
    year: 2003,
    link: "https://www.youtube.com/watch?v=7gwO8-oqwFw&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=183",
  },
  {
    artist: "The Red Jumpsuit Apparatus",
    name: "Face Down",
    year: 2006,
    link: "https://www.youtube.com/watch?v=6Ux6SlOE9Qk&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=184",
  },
  {
    artist: "The Killers",
    name: "Human",
    year: 2008,
    link: "https://www.youtube.com/watch?v=RIZdjT1472Y&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=185",
  },
  {
    artist: "The Pussycat Dolls ft. will.i.am",
    name: "Beep",
    year: 2005,
    link: "https://www.youtube.com/watch?v=1r9ghI7YcL0&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=186",
  },
  {
    artist: "The Script",
    name: "The Man Who Can't Be Moved",
    year: 2008,
    link: "https://www.youtube.com/watch?v=gS9o1FAszdk&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=187",
  },
  {
    artist: "The Veronicas",
    name: "Untouched",
    year: 2007,
    link: "https://www.youtube.com/watch?v=ykW4rtW2eu0&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=188",
  },
  {
    artist: "The White Stripes",
    name: "Seven Nations Army",
    year: 2003,
    link: "https://www.youtube.com/watch?v=0J2QdDbelmY&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=189",
  },
  {
    artist: "Timbaland ft Keri Hilson & D.O.E.",
    name: "The Way I Are",
    year: 2007,
    link: "https://www.youtube.com/watch?v=U5rLz5AZBIA&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=190",
  },
  {
    artist: "Toni Braxton",
    name: "He Wasn't Man Enough",
    year: 2000,
    link: "https://www.youtube.com/watch?v=9_hKXk2qSuw&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=191",
  },
  {
    artist: "Train",
    name: "Hey Soul Sister",
    year: 2009,
    link: "https://www.youtube.com/watch?v=kVpv8-5XWOI&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=192",
  },
  {
    artist: "Trapt",
    name: "Headstrong",
    year: 2002,
    link: "https://www.youtube.com/watch?v=HTvu1Yr3Ohk&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=193",
  },
  {
    artist: "Travis",
    name: "Sing",
    year: 2001,
    link: "https://www.youtube.com/watch?v=eYO1-gGWJyo&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=194",
  },
  {
    artist: "U2",
    name: "Beautiful Day",
    year: 2000,
    link: "https://www.youtube.com/watch?v=co6WMzDOh1o&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=195",
  },
  {
    artist: "Usher ft. Lil Jon & Ludacris",
    name: "Yeah!",
    year: 2004,
    link: "https://www.youtube.com/watch?v=GxBSyx85Kp8&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=196",
  },
  {
    artist: "Vanessa Carlton",
    name: "A Thousand Miles",
    year: 2002,
    link: "https://www.youtube.com/watch?v=Cwkej79U3ek&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=197",
  },
  {
    artist: "Weezer",
    name: "Island In The Sun",
    year: 2001,
    link: "https://www.youtube.com/watch?v=erG5rgNYSdk&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=198",
  },
  {
    artist: "Westlife",
    name: "When You're Looking Like That",
    year: 2001,
    link: "https://www.youtube.com/watch?v=5rmKy8H62BU&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=199",
  },
  {
    artist: "Wheatus",
    name: "Teenage Dirtbag",
    year: 2000,
    link: "https://www.youtube.com/watch?v=FC3y9llDXuM&list=PLxby-Vutx9UABGpxFzjJ5q-1J5NFgWwpq&index=200",
  },
];

songs.forEach((c) => {
  c.daScore = daScore[c.name];
  c.kukiScore = kukiScore[c.name];
  c.uniScore = uniScore[c.name];
  c.avgScore = Number(((c.daScore + c.kukiScore + c.uniScore) / 3).toFixed(2));
  c.bestScore = Math.min(c.daScore, c.uniScore, c.kukiScore);
});

songs.sort((a, b) => {
  if (a.avgScore !== b.avgScore) {
    return b.avgScore - a.avgScore;
  } else {
    if (a.bestScore !== b.bestScore) {
      return b.bestScore - a.bestScore;
    }
  }
  return a.name.localeCompare(b.name);
});

export default songs;
